### ISSUE TITLE
Allow external deprecated

### ISSUE THREAD

**Issue by borisroman** [MissionCriticalCloud/bubble-toolkit#67]
```
DEPRECATION: --allow-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
```

**Comment by miguelaferreira** [comment]
@borisroman can you be a bit more specific? Where is this being used? What were you doing when you figured this out? Anything else that can help people reading this understand you better?

**Comment by borisroman** [comment]
Sorry, was a mental note... ;)

It's in the build_run.sh script. Used when installing marvin with the mysql connector.

https://github.com/MissionCriticalCloud/bubble/blob/master/helper_scripts/cloudstack/build_run.sh#L28

**Comment by miguelaferreira** [comment]
Check! Thanks for the update.

**Comment by miguelaferreira** [comment]
Does the deprecation warning mean we can simply remove it and the install still works?

**Comment by borisroman** [comment]
Will try!
